#!/bin/bash
#######################################################################
# Copyright Lukas Bürgi 2019
#
# This file is part of km-stat.
#
# km-stat is free software: you can redistribute it and/or modify it
# under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# km-stat is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public
# License along with km-stat.  If not, see
# <https://www.gnu.org/licenses/>.
########################################################################
# I apologize for the way this file was written
# (using search and replace in a text editor)
# It definitely was easier than adapting the supplied script.

# How to use: Make a new folder next to the src folder with the svgs
# Change into it. Run the script.
set -euxo pipefail # be careful

WIDTH=20

inkscape "../src/afghanistan.svg" --export-width=$WIDTH --export-png=af.png 
inkscape "../src/albania.svg" --export-width=$WIDTH --export-png=al.png 
inkscape "../src/algeria.svg" --export-width=$WIDTH --export-png=dz.png 
inkscape "../src/andorra.svg" --export-width=$WIDTH --export-png=ad.png 
inkscape "../src/angola.svg" --export-width=$WIDTH --export-png=ao.png 
inkscape "../src/antarctica.svg" --export-width=$WIDTH --export-png=aq.png 
inkscape "../src/argentina.svg" --export-width=$WIDTH --export-png=ar.png 
inkscape "../src/armenia.svg" --export-width=$WIDTH --export-png=am.png 
inkscape "../src/australia.svg" --export-width=$WIDTH --export-png=au.png 
inkscape "../src/austria.svg" --export-width=$WIDTH --export-png=at.png 
inkscape "../src/azerbaijan.svg" --export-width=$WIDTH --export-png=az.png 
inkscape "../src/bahrain.svg" --export-width=$WIDTH --export-png=bh.png 
inkscape "../src/bangladesh.svg" --export-width=$WIDTH --export-png=bd.png 
inkscape "../src/barbados.svg" --export-width=$WIDTH --export-png=bb.png 
inkscape "../src/belarus.svg" --export-width=$WIDTH --export-png=by.png 
inkscape "../src/belgium.svg" --export-width=$WIDTH --export-png=be.png 
inkscape "../src/belize.svg" --export-width=$WIDTH --export-png=bz.png 
inkscape "../src/benin.svg" --export-width=$WIDTH --export-png=bj.png 
inkscape "../src/bhutan.svg" --export-width=$WIDTH --export-png=bt.png 
inkscape "../src/bolivia.svg" --export-width=$WIDTH --export-png=bo.png 
inkscape "../src/bosnia_and_herzegovina.svg" --export-width=$WIDTH --export-png=ba.png 
inkscape "../src/botswana.svg" --export-width=$WIDTH --export-png=bw.png 
inkscape "../src/brazil.svg" --export-width=$WIDTH --export-png=br.png 
inkscape "../src/brunei_darussalam.svg" --export-width=$WIDTH --export-png=bn.png 
inkscape "../src/bulgaria.svg" --export-width=$WIDTH --export-png=bg.png 
inkscape "../src/burkina_faso.svg" --export-width=$WIDTH --export-png=bf.png 
inkscape "../src/burundi.svg" --export-width=$WIDTH --export-png=bi.png 
inkscape "../src/cambodia.svg" --export-width=$WIDTH --export-png=kh.png 
inkscape "../src/cameroon.svg" --export-width=$WIDTH --export-png=cm.png 
inkscape "../src/canada.svg" --export-width=$WIDTH --export-png=ca.png 
inkscape "../src/capeverde.svg" --export-width=$WIDTH --export-png=cv.png 
inkscape "../src/central_african_republic.svg" --export-width=$WIDTH --export-png=cf.png 
inkscape "../src/chad.svg" --export-width=$WIDTH --export-png=td.png 
inkscape "../src/chile.svg" --export-width=$WIDTH --export-png=cl.png 
inkscape "../src/china.svg" --export-width=$WIDTH --export-png=cn.png 
inkscape "../src/colombia.svg" --export-width=$WIDTH --export-png=co.png 
inkscape "../src/comoros.svg" --export-width=$WIDTH --export-png=km.png 
inkscape "../src/congo_brazzaville.svg" --export-width=$WIDTH --export-png=cg.png 
inkscape "../src/congo_kinshasa.svg" --export-width=$WIDTH --export-png=cd.png 
inkscape "../src/cook_islands.svg" --export-width=$WIDTH --export-png=ck.png 
inkscape "../src/costa_rica.svg" --export-width=$WIDTH --export-png=cr.png 
inkscape "../src/cote_divoire.svg" --export-width=$WIDTH --export-png=ci.png 
inkscape "../src/croatia.svg" --export-width=$WIDTH --export-png=hr.png 
inkscape "../src/cuba.svg" --export-width=$WIDTH --export-png=cu.png 
inkscape "../src/cyprus.svg" --export-width=$WIDTH --export-png=cy.png 
inkscape "../src/czech_republic.svg" --export-width=$WIDTH --export-png=cz.png 
inkscape "../src/denmark.svg" --export-width=$WIDTH --export-png=dk.png 
inkscape "../src/djibouti.svg" --export-width=$WIDTH --export-png=dj.png 
inkscape "../src/dominican_republic.svg" --export-width=$WIDTH --export-png=do.png 
inkscape "../src/dominica.svg" --export-width=$WIDTH --export-png=dm.png 
inkscape "../src/ecuador.svg" --export-width=$WIDTH --export-png=ec.png 
inkscape "../src/egypt.svg" --export-width=$WIDTH --export-png=eg.png 
inkscape "../src/el_salvador.svg" --export-width=$WIDTH --export-png=sv.png 
inkscape "../src/equatorial_guinea.svg" --export-width=$WIDTH --export-png=gq.png 
inkscape "../src/eritrea.svg" --export-width=$WIDTH --export-png=er.png 
inkscape "../src/estonia.svg" --export-width=$WIDTH --export-png=ee.png 
inkscape "../src/ethiopia.svg" --export-width=$WIDTH --export-png=et.png 
inkscape "../src/fiji.svg" --export-width=$WIDTH --export-png=fj.png 
inkscape "../src/finland.svg" --export-width=$WIDTH --export-png=fi.png 
inkscape "../src/france.svg" --export-width=$WIDTH --export-png=fr.png 
inkscape "../src/gabon.svg" --export-width=$WIDTH --export-png=ga.png 
inkscape "../src/gambia.svg" --export-width=$WIDTH --export-png=gm.png 
inkscape "../src/georgia.svg" --export-width=$WIDTH --export-png=ge.png 
inkscape "../src/germany.svg" --export-width=$WIDTH --export-png=de.png 
inkscape "../src/ghana.svg" --export-width=$WIDTH --export-png=gh.png 
inkscape "../src/greece.svg" --export-width=$WIDTH --export-png=gr.png 
inkscape "../src/grenada.svg" --export-width=$WIDTH --export-png=gd.png 
inkscape "../src/guatemala.svg" --export-width=$WIDTH --export-png=gt.png 
inkscape "../src/guinea_bissau.svg" --export-width=$WIDTH --export-png=gw.png 
inkscape "../src/guinea.svg" --export-width=$WIDTH --export-png=gn.png 
inkscape "../src/guyana.svg" --export-width=$WIDTH --export-png=gy.png 
inkscape "../src/haiti.svg" --export-width=$WIDTH --export-png=ht.png 
inkscape "../src/honduras.svg" --export-width=$WIDTH --export-png=hn.png 
inkscape "../src/hungary.svg" --export-width=$WIDTH --export-png=hu.png 
inkscape "../src/iceland.svg" --export-width=$WIDTH --export-png=is.png 
inkscape "../src/india.svg" --export-width=$WIDTH --export-png=in.png 
inkscape "../src/indonesia.svg" --export-width=$WIDTH --export-png=id.png 
inkscape "../src/iran.svg" --export-width=$WIDTH --export-png=ir.png 
inkscape "../src/iraq.svg" --export-width=$WIDTH --export-png=iq.png 
inkscape "../src/ireland.svg" --export-width=$WIDTH --export-png=ie.png 
inkscape "../src/israel.svg" --export-width=$WIDTH --export-png=il.png 
inkscape "../src/italy.svg" --export-width=$WIDTH --export-png=it.png 
inkscape "../src/jamaica.svg" --export-width=$WIDTH --export-png=jm.png 
inkscape "../src/japan.svg" --export-width=$WIDTH --export-png=jp.png 
inkscape "../src/jordan.svg" --export-width=$WIDTH --export-png=jo.png 
inkscape "../src/kazakhstan.svg" --export-width=$WIDTH --export-png=kz.png 
inkscape "../src/kenya.svg" --export-width=$WIDTH --export-png=ke.png 
inkscape "../src/kiribati.svg" --export-width=$WIDTH --export-png=ki.png 
inkscape "../src/kuwait.svg" --export-width=$WIDTH --export-png=kw.png 
inkscape "../src/kyrgyzstan.svg" --export-width=$WIDTH --export-png=kg.png 
inkscape "../src/laos.svg" --export-width=$WIDTH --export-png=la.png 
inkscape "../src/latvia.svg" --export-width=$WIDTH --export-png=lv.png 
inkscape "../src/lebanon.svg" --export-width=$WIDTH --export-png=lb.png 
inkscape "../src/lesotho.svg" --export-width=$WIDTH --export-png=ls.png 
inkscape "../src/liberia.svg" --export-width=$WIDTH --export-png=lr.png 
inkscape "../src/libyan_arab_jamahiriya.svg" --export-width=$WIDTH --export-png=ly.png 
inkscape "../src/liechtenstein.svg" --export-width=$WIDTH --export-png=li.png 
inkscape "../src/lithuania.svg" --export-width=$WIDTH --export-png=lt.png 
inkscape "../src/luxembourg.svg" --export-width=$WIDTH --export-png=lu.png 
inkscape "../src/macedonia.svg" --export-width=$WIDTH --export-png=mk.png 
inkscape "../src/madagascar.svg" --export-width=$WIDTH --export-png=mg.png 
inkscape "../src/malawi.svg" --export-width=$WIDTH --export-png=mw.png 
inkscape "../src/malaysia.svg" --export-width=$WIDTH --export-png=my.png 
inkscape "../src/maldives.svg" --export-width=$WIDTH --export-png=mv.png 
inkscape "../src/mali.svg" --export-width=$WIDTH --export-png=ml.png 
inkscape "../src/malta.svg" --export-width=$WIDTH --export-png=mt.png 
inkscape "../src/mauritania.svg" --export-width=$WIDTH --export-png=mr.png 
inkscape "../src/mauritius.svg" --export-width=$WIDTH --export-png=mu.png 
inkscape "../src/mexico.svg" --export-width=$WIDTH --export-png=mx.png 
inkscape "../src/micronesia.svg" --export-width=$WIDTH --export-png=fm.png 
inkscape "../src/moldova.svg" --export-width=$WIDTH --export-png=md.png 
inkscape "../src/monaco.svg" --export-width=$WIDTH --export-png=mc.png 
inkscape "../src/mongolia.svg" --export-width=$WIDTH --export-png=mn.png 
inkscape "../src/morocco.svg" --export-width=$WIDTH --export-png=ma.png 
inkscape "../src/mozambique.svg" --export-width=$WIDTH --export-png=mz.png 
inkscape "../src/myanmar.svg" --export-width=$WIDTH --export-png=mm.png 
inkscape "../src/namibia.svg" --export-width=$WIDTH --export-png=na.png 
inkscape "../src/nauru.svg" --export-width=$WIDTH --export-png=nr.png 
inkscape "../src/nepal.svg" --export-width=$WIDTH --export-png=np.png 
inkscape "../src/netherlands.svg" --export-width=$WIDTH --export-png=nl.png 
inkscape "../src/newzealand.svg" --export-width=$WIDTH --export-png=nz.png 
inkscape "../src/nicaragua.svg" --export-width=$WIDTH --export-png=ni.png 
inkscape "../src/nigeria.svg" --export-width=$WIDTH --export-png=ng.png 
inkscape "../src/niger.svg" --export-width=$WIDTH --export-png=ne.png 
inkscape "../src/niue.svg" --export-width=$WIDTH --export-png=nu.png 
inkscape "../src/northern_mariana.svg" --export-width=$WIDTH --export-png=mp.png 
inkscape "../src/north_korea.svg" --export-width=$WIDTH --export-png=kp.png 
inkscape "../src/norway.svg" --export-width=$WIDTH --export-png=no.png 
inkscape "../src/oman.svg" --export-width=$WIDTH --export-png=om.png 
inkscape "../src/pakistan.svg" --export-width=$WIDTH --export-png=pk.png 
inkscape "../src/palau.svg" --export-width=$WIDTH --export-png=pw.png 
inkscape "../src/palestine.svg" --export-width=$WIDTH --export-png=ps.png 
inkscape "../src/panama.svg" --export-width=$WIDTH --export-png=pa.png 
inkscape "../src/papua_new_guinea.svg" --export-width=$WIDTH --export-png=pg.png 
inkscape "../src/paraguay.svg" --export-width=$WIDTH --export-png=py.png 
inkscape "../src/peru.svg" --export-width=$WIDTH --export-png=pe.png 
inkscape "../src/philippines.svg" --export-width=$WIDTH --export-png=ph.png 
inkscape "../src/poland.svg" --export-width=$WIDTH --export-png=pl.png 
inkscape "../src/portugal.svg" --export-width=$WIDTH --export-png=pt.png 
inkscape "../src/puerto_rico.svg" --export-width=$WIDTH --export-png=pr.png 
inkscape "../src/qatar.svg" --export-width=$WIDTH --export-png=qa.png 
inkscape "../src/romania.svg" --export-width=$WIDTH --export-png=ro.png 
inkscape "../src/russian_federation.svg" --export-width=$WIDTH --export-png=ru.png 
inkscape "../src/rwanda.svg" --export-width=$WIDTH --export-png=rw.png 
inkscape "../src/saint_kitts_and_nevis.svg" --export-width=$WIDTH --export-png=kn.png 
inkscape "../src/saint_lucia.svg" --export-width=$WIDTH --export-png=lc.png 
inkscape "../src/saint_vincent_and_the_grenadines.svg" --export-width=$WIDTH --export-png=vc.png 
inkscape "../src/samoa.svg" --export-width=$WIDTH --export-png=ws.png 
inkscape "../src/san_marino.svg" --export-width=$WIDTH --export-png=sm.png 
inkscape "../src/sao_tome_and_principe.svg" --export-width=$WIDTH --export-png=st.png 
inkscape "../src/saudi_arabia.svg" --export-width=$WIDTH --export-png=sa.png 
inkscape "../src/senegal.svg" --export-width=$WIDTH --export-png=sn.png 
inkscape "../src/serbia_and_montenegro.svg" --export-width=$WIDTH --export-png=yu.png
inkscape "../src/serbia.svg" --export-width=$WIDTH --export-png=rs.png 
inkscape "../src/seychelles.svg" --export-width=$WIDTH --export-png=sc.png 
inkscape "../src/sierra_leone.svg" --export-width=$WIDTH --export-png=sl.png 
inkscape "../src/singapore.svg" --export-width=$WIDTH --export-png=sg.png 
inkscape "../src/slovakia.svg" --export-width=$WIDTH --export-png=sk.png 
inkscape "../src/slovenia.svg" --export-width=$WIDTH --export-png=si.png 
inkscape "../src/solomonislands.svg" --export-width=$WIDTH --export-png=sb.png 
inkscape "../src/somalia.svg" --export-width=$WIDTH --export-png=so.png 
inkscape "../src/south_africa.svg" --export-width=$WIDTH --export-png=za.png 
inkscape "../src/south_korea.svg" --export-width=$WIDTH --export-png=kr.png 
inkscape "../src/spain.svg" --export-width=$WIDTH --export-png=es.png 
inkscape "../src/sri_lanka.svg" --export-width=$WIDTH --export-png=lk.png 
inkscape "../src/sudan.svg" --export-width=$WIDTH --export-png=sd.png 
inkscape "../src/suisse.svg" --export-width=$WIDTH --export-png=ch.png 
inkscape "../src/suriname.svg" --export-width=$WIDTH --export-png=sr.png 
inkscape "../src/swaziland.svg" --export-width=$WIDTH --export-png=sz.png 
inkscape "../src/sweden.svg" --export-width=$WIDTH --export-png=se.png 
inkscape "../src/syrian_arab_republic.svg" --export-width=$WIDTH --export-png=sy.png 
inkscape "../src/taiwan.svg" --export-width=$WIDTH --export-png=tw.png 
inkscape "../src/tajikistan.svg" --export-width=$WIDTH --export-png=tj.png 
inkscape "../src/tanzania.svg" --export-width=$WIDTH --export-png=tz.png 
inkscape "../src/thailand.svg" --export-width=$WIDTH --export-png=th.png 
inkscape "../src/timor_leste.svg" --export-width=$WIDTH --export-png=tp.png 
inkscape "../src/togo.svg" --export-width=$WIDTH --export-png=tg.png 
inkscape "../src/tonga.svg" --export-width=$WIDTH --export-png=to.png 
inkscape "../src/trinidad_and_tobago.svg" --export-width=$WIDTH --export-png=tt.png 
inkscape "../src/tunisia.svg" --export-width=$WIDTH --export-png=tn.png 
inkscape "../src/turkey.svg" --export-width=$WIDTH --export-png=tr.png 
inkscape "../src/turkmenistan.svg" --export-width=$WIDTH --export-png=tm.png 
inkscape "../src/tuvalu.svg" --export-width=$WIDTH --export-png=tv.png 
inkscape "../src/uganda.svg" --export-width=$WIDTH --export-png=ug.png 
inkscape "../src/ukraine.svg" --export-width=$WIDTH --export-png=ua.png 
inkscape "../src/united_arab_emirates.svg" --export-width=$WIDTH --export-png=ae.png 
inkscape "../src/united_kingdom.svg" --export-width=$WIDTH --export-png=gb.png 
inkscape "../src/united_states.svg" --export-width=$WIDTH --export-png=us.png 
inkscape "../src/uruguay.svg" --export-width=$WIDTH --export-png=uy.png 
inkscape "../src/uzbekistan.svg" --export-width=$WIDTH --export-png=uz.png 
inkscape "../src/vanuatu.svg" --export-width=$WIDTH --export-png=vu.png 
inkscape "../src/vatican.svg" --export-width=$WIDTH --export-png=va.png 
inkscape "../src/venezuela.svg" --export-width=$WIDTH --export-png=ve.png 
inkscape "../src/vietnam.svg" --export-width=$WIDTH --export-png=vn.png 
inkscape "../src/western_sahara.svg" --export-width=$WIDTH --export-png=eh.png 
inkscape "../src/yemen.svg" --export-width=$WIDTH --export-png=ye.png 
inkscape "../src/zambia.svg" --export-width=$WIDTH --export-png=zm.png 
inkscape "../src/zimbabwe.svg" --export-width=$WIDTH --export-png=zw.png 
inkscape "../src/australia_capital_territory.svg" --export-width=$WIDTH --export-png=au-act.png 
inkscape "../src/australia_christmas_island.svg" --export-width=$WIDTH --export-png=au-cx.png 
inkscape "../src/australia_lord_howe_island.svg" --export-width=$WIDTH --export-png=au-lhi.png 
inkscape "../src/australia_norfolk_island.svg" --export-width=$WIDTH --export-png=au-nf.png 
inkscape "../src/australia_northern_territory.svg" --export-width=$WIDTH --export-png=au-nt.png 
inkscape "../src/australia_new_south_wales.svg" --export-width=$WIDTH --export-png=au-nsw.png 
inkscape "../src/australia_queensland.svg" --export-width=$WIDTH --export-png=au-qld.png 
inkscape "../src/australia_south_australia.svg" --export-width=$WIDTH --export-png=au-sa.png 
inkscape "../src/australia_tasmania.svg" --export-width=$WIDTH --export-png=au-tas.png 
inkscape "../src/australia_victoria.svg" --export-width=$WIDTH --export-png=au-vic.png 
inkscape "../src/australia_western_australia.svg" --export-width=$WIDTH --export-png=au-wa.png 
inkscape "../src/canada_acadia.svg" --export-width=$WIDTH --export-png=ca-ac.png 
inkscape "../src/canada_alberta.svg" --export-width=$WIDTH --export-png=ca-ab.png 
inkscape "../src/canada_british_columbia.svg" --export-width=$WIDTH --export-png=ca-bc.png 
inkscape "../src/canada_manitoba.svg" --export-width=$WIDTH --export-png=ca-mb.png 
inkscape "../src/canada_new_brunswick.svg" --export-width=$WIDTH --export-png=ca-nb.png 
inkscape "../src/canada_newfoundland.svg" --export-width=$WIDTH --export-png=ca-nf.png 
inkscape "../src/canada_northwest_territories.svg" --export-width=$WIDTH --export-png=ca-nt.png 
inkscape "../src/canada_nova_scotia.svg" --export-width=$WIDTH --export-png=ca-ns.png 
inkscape "../src/canada_nunavut.svg" --export-width=$WIDTH --export-png=ca-nu.png 
inkscape "../src/canada_ontario.svg" --export-width=$WIDTH --export-png=ca-on.png 
inkscape "../src/canada_prince_edward_island.svg" --export-width=$WIDTH --export-png=ca-pe.png 
inkscape "../src/canada_quebec.svg" --export-width=$WIDTH --export-png=ca-qc.png 
inkscape "../src/canada_saskatchewan.svg" --export-width=$WIDTH --export-png=ca-sk.png 
inkscape "../src/canada_yukon.svg" --export-width=$WIDTH --export-png=ca-yu.png 
inkscape "../src/china_hong_kong.svg" --export-width=$WIDTH --export-png=cn-hk.png 
inkscape "../src/china_macao.svg" --export-width=$WIDTH --export-png=cn-mo.png 
inkscape "../src/denmark_faroe.svg" --export-width=$WIDTH --export-png=dk-fo.png 
inkscape "../src/denmark_greenland.svg" --export-width=$WIDTH --export-png=dk-gl.png 
inkscape "../src/europeanunion.svg" --export-width=$WIDTH --export-png=eu.png 
inkscape "../src/guadeloupe.svg" --export-width=$WIDTH --export-png=fr-gp.png 
inkscape "../src/martinique.svg" --export-width=$WIDTH --export-png=fr-mq.png 
inkscape "../src/new_caledonia.svg" --export-width=$WIDTH --export-png=fr-nc.png 
inkscape "../src/french_polynesia.svg" --export-width=$WIDTH --export-png=fr-pf.png 
inkscape "../src/st_pierre_and_miquelon.svg" --export-width=$WIDTH --export-png=fr-pm.png 
inkscape "../src/reunion.svg" --export-width=$WIDTH --export-png=fr-re.png 
inkscape "../src/french_austral_territories.svg" --export-width=$WIDTH --export-png=fr-ta.png 
inkscape "../src/wallis_and_futuna.svg" --export-width=$WIDTH --export-png=fr-wf.png 
inkscape "../src/mayotte.svg" --export-width=$WIDTH --export-png=fr-yt.png 
inkscape "../src/netherlands_antilles.svg" --export-width=$WIDTH --export-png=nl-an.png 
inkscape "../src/aruba.svg" --export-width=$WIDTH --export-png=nl-aw.png 
inkscape "../src/spain_baleares.svg" --export-width=$WIDTH --export-png=es-ib.png 
inkscape "../src/spain_canary.svg" --export-width=$WIDTH --export-png=es-ic.png 
inkscape "../src/portugal_azores.svg" --export-width=$WIDTH --export-png=pt-az.png 
inkscape "../src/portugal_madeira.svg" --export-width=$WIDTH --export-png=pt-md.png 
inkscape "../src/uk_england.svg" --export-width=$WIDTH --export-png=gb-en.png 
inkscape "../src/uk_guernsey.svg" --export-width=$WIDTH --export-png=gb-gg.png 
inkscape "../src/uk_gibraltar.svg" --export-width=$WIDTH --export-png=gb-gi.png 
inkscape "../src/uk_isle_of_man.svg" --export-width=$WIDTH --export-png=gb-im.png 
inkscape "../src/uk_jersey.svg" --export-width=$WIDTH --export-png=gb-je.png 
inkscape "../src/uk_kernow.svg" --export-width=$WIDTH --export-png=gb-kn.png 
inkscape "../src/uk_northern_ireland.svg" --export-width=$WIDTH --export-png=gb-ni.png 
inkscape "../src/uk_orkney.svg" --export-width=$WIDTH --export-png=gb-or.png 
inkscape "../src/uk_scotland.svg" --export-width=$WIDTH --export-png=gb-sc.png 
inkscape "../src/uk_shetland.svg" --export-width=$WIDTH --export-png=gb-se.png 
inkscape "../src/uk_wales.svg" --export-width=$WIDTH --export-png=gb-wa.png 
inkscape "../src/anguilla.svg" --export-width=$WIDTH --export-png=gb-ai.png 
inkscape "../src/bermuda.svg" --export-width=$WIDTH --export-png=gb-bm.png 
inkscape "../src/falkland_islands.svg" --export-width=$WIDTH --export-png=gb-fk.png 
inkscape "../src/south_georgia_and_south_sandwich_islands.svg" --export-width=$WIDTH --export-png=gb-gs.png 
inkscape "../src/uk_british_indian_ocean_territory.svg" --export-width=$WIDTH --export-png=gb-io.png 
inkscape "../src/cayman_islands.svg" --export-width=$WIDTH --export-png=gb-ky.png 
inkscape "../src/montserrat.svg" --export-width=$WIDTH --export-png=gb-ms.png 
inkscape "../src/pitcairn_islands.svg" --export-width=$WIDTH --export-png=gb-pn.png 
inkscape "../src/saint_helena.svg" --export-width=$WIDTH --export-png=gb-sh.png 
inkscape "../src/turks_and_caicos.svg" --export-width=$WIDTH --export-png=gb-tc.png 
inkscape "../src/british_virgin_islands.svg" --export-width=$WIDTH --export-png=gb-vg.png 
inkscape "../src/usa_alaska.svg" --export-width=$WIDTH --export-png=us-ak.png 
inkscape "../src/usa_alabama.svg" --export-width=$WIDTH --export-png=us-al.png 
inkscape "../src/usa_arkansas.svg" --export-width=$WIDTH --export-png=us-ar.png 
inkscape "../src/usa_arizona.svg" --export-width=$WIDTH --export-png=us-az.png 
inkscape "../src/usa_california.svg" --export-width=$WIDTH --export-png=us-ca.png 
inkscape "../src/usa_colorado.svg" --export-width=$WIDTH --export-png=us-co.png 
inkscape "../src/usa_connecticut.svg" --export-width=$WIDTH --export-png=us-ct.png 
inkscape "../src/usa_district_of_columbia.svg" --export-width=$WIDTH --export-png=us-dc.png 
inkscape "../src/usa_delaware.svg" --export-width=$WIDTH --export-png=us-de.png 
inkscape "../src/usa_florida.svg" --export-width=$WIDTH --export-png=us-fl.png 
inkscape "../src/usa_georgia.svg" --export-width=$WIDTH --export-png=us-ga.png 
inkscape "../src/usa_hawaii.svg" --export-width=$WIDTH --export-png=us-hi.png 
inkscape "../src/usa_iowa.svg" --export-width=$WIDTH --export-png=us-ia.png 
inkscape "../src/usa_idaho.svg" --export-width=$WIDTH --export-png=us-id.png 
inkscape "../src/usa_illinois.svg" --export-width=$WIDTH --export-png=us-il.png 
inkscape "../src/usa_indiana.svg" --export-width=$WIDTH --export-png=us-in.png 
inkscape "../src/usa_kansas.svg" --export-width=$WIDTH --export-png=us-ks.png 
inkscape "../src/usa_kentucky.svg" --export-width=$WIDTH --export-png=us-ky.png 
inkscape "../src/usa_louisiana.svg" --export-width=$WIDTH --export-png=us-la.png 
inkscape "../src/usa_massachusetts.svg" --export-width=$WIDTH --export-png=us-ma.png 
inkscape "../src/usa_maryland.svg" --export-width=$WIDTH --export-png=us-md.png 
inkscape "../src/usa_maine.svg" --export-width=$WIDTH --export-png=us-me.png 
inkscape "../src/usa_michigan.svg" --export-width=$WIDTH --export-png=us-mi.png 
inkscape "../src/usa_minnesota.svg" --export-width=$WIDTH --export-png=us-mn.png 
inkscape "../src/usa_missouri.svg" --export-width=$WIDTH --export-png=us-mo.png 
inkscape "../src/usa_mississippi.svg" --export-width=$WIDTH --export-png=us-ms.png 
inkscape "../src/usa_montana.svg" --export-width=$WIDTH --export-png=us-mt.png 
inkscape "../src/usa_northcarolina.svg" --export-width=$WIDTH --export-png=us-nc.png 
inkscape "../src/usa_northdakota.svg" --export-width=$WIDTH --export-png=us-nd.png 
inkscape "../src/usa_nebraska.svg" --export-width=$WIDTH --export-png=us-ne.png 
inkscape "../src/usa_newhampshire.svg" --export-width=$WIDTH --export-png=us-nh.png 
inkscape "../src/usa_newjersey.svg" --export-width=$WIDTH --export-png=us-nj.png 
inkscape "../src/usa_newmexico.svg" --export-width=$WIDTH --export-png=us-nm.png 
inkscape "../src/usa_nevada.svg" --export-width=$WIDTH --export-png=us-nv.png 
inkscape "../src/usa_newyork.svg" --export-width=$WIDTH --export-png=us-ny.png 
inkscape "../src/usa_ohio.svg" --export-width=$WIDTH --export-png=us-oh.png 
inkscape "../src/usa_oklahoma.svg" --export-width=$WIDTH --export-png=us-ok.png 
inkscape "../src/usa_oregon.svg" --export-width=$WIDTH --export-png=us-or.png 
inkscape "../src/usa_pennsylvania.svg" --export-width=$WIDTH --export-png=us-pa.png 
inkscape "../src/usa_rhode_island.svg" --export-width=$WIDTH --export-png=us-ri.png 
inkscape "../src/usa_southcarolina.svg" --export-width=$WIDTH --export-png=us-sc.png 
inkscape "../src/usa_southdakota.svg" --export-width=$WIDTH --export-png=us-sd.png 
inkscape "../src/usa_tennessee.svg" --export-width=$WIDTH --export-png=us-tn.png 
inkscape "../src/usa_texas.svg" --export-width=$WIDTH --export-png=us-tx.png 
inkscape "../src/usa_utah.svg" --export-width=$WIDTH --export-png=us-ut.png 
inkscape "../src/usa_virginia.svg" --export-width=$WIDTH --export-png=us-va.png 
inkscape "../src/usa_vermont.svg" --export-width=$WIDTH --export-png=us-vt.png 
inkscape "../src/usa_washington.svg" --export-width=$WIDTH --export-png=us-wa.png 
inkscape "../src/usa_wisconsin.svg" --export-width=$WIDTH --export-png=us-wi.png 
inkscape "../src/usa_westvirginia.svg" --export-width=$WIDTH --export-png=us-wv.png 
inkscape "../src/usa_wyoming.svg" --export-width=$WIDTH --export-png=us-wy.png 
inkscape "../src/american_samoa.svg" --export-width=$WIDTH --export-png=us-as.png 
inkscape "../src/antigua_and_barbuda.svg" --export-width=$WIDTH --export-png=us-ag.png 
inkscape "../src/bahamas.svg" --export-width=$WIDTH --export-png=us-bs.png 
inkscape "../src/guam.svg" --export-width=$WIDTH --export-png=us-gu.png 
inkscape "../src/marshall_islands.svg" --export-width=$WIDTH --export-png=us-mh.png 
inkscape "../src/usa_virgin_islands.svg" --export-width=$WIDTH --export-png=us-vi.png 
inkscape "../src/wake_island.svg" --export-width=$WIDTH --export-png=us-wk.png
