# Generated by Django 2.1.7 on 2019-03-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exportkontrollnummern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Geschaefte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.PositiveIntegerField(blank=True, null=True)),
                ('umfang', models.PositiveIntegerField()),
                ('beginn', models.DateField()),
                ('ende', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Geschaeftsrichtungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Geschaeftstypen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Kontrollregimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Laender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemArten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ausschlusskriterium', models.BooleanField()),
                ('faktor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ProblemArtenGesetz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gesetz', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Probleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginn', models.DateField()),
                ('ende', models.DateField()),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.ProblemArten')),
                ('betroffenesGeschaeft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Geschaefte')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Laender')),
            ],
        ),
        migrations.CreateModel(
            name='QuellenGeschaefte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download', models.FileField(upload_to='')),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='QuellenProbleme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('linkText', models.CharField(max_length=200)),
                ('sprache', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Uebersetzungen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.TextField()),
                ('fr', models.TextField()),
                ('it', models.TextField()),
                ('en', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='quellengeschaefte',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen'),
        ),
        migrations.AddField(
            model_name='probleme',
            name='quellen',
            field=models.ManyToManyField(to='exportkontrollstatistiken.QuellenProbleme'),
        ),
        migrations.AddField(
            model_name='probleme',
            name='zusammenfassung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen'),
        ),
        migrations.AddField(
            model_name='problemarten',
            name='gesetz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.ProblemArtenGesetz'),
        ),
        migrations.AddField(
            model_name='problemarten',
            name='kurzbeschreibung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen'),
        ),
        migrations.AddField(
            model_name='laender',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen'),
        ),
        migrations.AddField(
            model_name='kontrollregimes',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen'),
        ),
        migrations.AddField(
            model_name='geschaeftstypen',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen'),
        ),
        migrations.AddField(
            model_name='geschaeftsrichtungen',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen'),
        ),
        migrations.AddField(
            model_name='geschaefte',
            name='bestimmungsland',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Laender'),
        ),
        migrations.AddField(
            model_name='geschaefte',
            name='exportkontrollnummer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Exportkontrollnummern'),
        ),
        migrations.AddField(
            model_name='geschaefte',
            name='kontrollregime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Kontrollregimes'),
        ),
        migrations.AddField(
            model_name='geschaefte',
            name='quelle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.QuellenGeschaefte'),
        ),
        migrations.AddField(
            model_name='geschaefte',
            name='richtung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Geschaeftsrichtungen'),
        ),
        migrations.AddField(
            model_name='geschaefte',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Geschaeftstypen'),
        ),
        migrations.AddField(
            model_name='exportkontrollnummern',
            name='beschreibung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen'),
        ),
        migrations.AddField(
            model_name='exportkontrollnummern',
            name='kontrollregime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Kontrollregimes'),
        ),
    ]
