# Generated by Django 2.1.7 on 2019-03-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uebersetzungen',
            name='de',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uebersetzungen',
            name='en',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uebersetzungen',
            name='fr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='uebersetzungen',
            name='it',
            field=models.TextField(blank=True),
        ),
    ]
