# Generated by Django 2.1.7 on 2019-03-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0002_auto_20190304_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quellengeschaefte',
            name='link',
            field=models.URLField(max_length=3000),
        ),
    ]
