# Generated by Django 2.1.7 on 2019-03-29 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0003_auto_20190305_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='GueterArten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Geschaeftstypen',
            new_name='Bewilligungstypen',
        ),
        migrations.AlterModelOptions(
            name='uebersetzungen',
            options={'verbose_name': 'Übersetzung', 'verbose_name_plural': 'Übersetzungen'},
        ),
        migrations.RenameField(
            model_name='geschaefte',
            old_name='typ',
            new_name='bewilligungstyp',
        ),
        migrations.RenameField(
            model_name='geschaefte',
            old_name='bestimmungsland',
            new_name='endempfaengerstaat',
        ),
        migrations.RemoveField(
            model_name='geschaefte',
            name='kontrollregime',
        ),
        migrations.AddField(
            model_name='kontrollregimes',
            name='aufgehobenwerden',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kontrollregimes',
            name='inkrafttreten',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exportkontrollnummern',
            name='beschreibung',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen'),
        ),
        migrations.AlterField(
            model_name='quellengeschaefte',
            name='download',
            field=models.FileField(upload_to='quellenGeschaefte/'),
        ),
        migrations.AddField(
            model_name='gueterarten',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen'),
        ),
        migrations.AddField(
            model_name='kontrollregimes',
            name='gueterArt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.GueterArten'),
            preserve_default=False,
        ),
    ]
