# Generated by Django 2.1.7 on 2019-03-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0004_auto_20190329_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bewilligungstypen',
            options={'verbose_name': 'Bewilligungstyp', 'verbose_name_plural': 'Bewilligungstypen'},
        ),
        migrations.AlterModelOptions(
            name='exportkontrollnummern',
            options={'verbose_name': 'Exportkontrollnummer', 'verbose_name_plural': 'Exportkontrollnummern'},
        ),
        migrations.AlterModelOptions(
            name='geschaefte',
            options={'verbose_name': 'Geschäft', 'verbose_name_plural': 'Geschäfte'},
        ),
        migrations.AlterModelOptions(
            name='geschaeftsrichtungen',
            options={'verbose_name': 'Geschäftsrichtung', 'verbose_name_plural': 'Geschäftsrichtungen'},
        ),
        migrations.AlterModelOptions(
            name='gueterarten',
            options={'verbose_name': 'Güterart', 'verbose_name_plural': 'Güterarten'},
        ),
        migrations.AlterModelOptions(
            name='kontrollregimes',
            options={'verbose_name': 'Kontrollregime', 'verbose_name_plural': 'Kontrollregimes'},
        ),
        migrations.AlterModelOptions(
            name='laender',
            options={'verbose_name': 'Land', 'verbose_name_plural': 'Länder'},
        ),
        migrations.AlterModelOptions(
            name='problemarten',
            options={'verbose_name': 'Problemart', 'verbose_name_plural': 'Problemarten'},
        ),
        migrations.AlterModelOptions(
            name='problemartengesetz',
            options={'verbose_name': 'Gesetz das Problemart stützt', 'verbose_name_plural': 'Gesetze die Problemarten stützten'},
        ),
        migrations.AlterModelOptions(
            name='probleme',
            options={'verbose_name': 'Problem', 'verbose_name_plural': 'Probleme'},
        ),
        migrations.AlterModelOptions(
            name='quellengeschaefte',
            options={'verbose_name': 'Quelle für Geschäfte', 'verbose_name_plural': 'Quellen für Geschäfte'},
        ),
        migrations.AlterModelOptions(
            name='quellenprobleme',
            options={'verbose_name': 'Quelle für Probleme', 'verbose_name_plural': 'Quellen für Probleme'},
        ),
        migrations.AlterField(
            model_name='kontrollregimes',
            name='aufgehobenwerden',
            field=models.DateField(blank=True, null=True),
        ),
    ]
