# Generated by Django 2.1.7 on 2019-03-29 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0005_auto_20190329_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportkontrollnummern',
            name='beschreibung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen'),
        ),
    ]
