# Generated by Django 2.1.7 on 2019-03-29 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0007_geschaefteimport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geschaefte',
            name='quelle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.QuellenGeschaefte'),
        ),
    ]
