# Generated by Django 2.1.7 on 2019-04-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0008_auto_20190329_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='laender',
            name='breitengradMax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laender',
            name='breitengradMin',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laender',
            name='laengengradMax',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laender',
            name='laengengradMin',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
