# Generated by Django 2.1.7 on 2019-04-09 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0009_auto_20190407_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geschaeftsjahressummen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umfang', models.PositiveIntegerField()),
                ('jahr', models.PositiveIntegerField()),
                ('endempfaengerstaat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Laender')),
                ('gueterArt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.GueterArten')),
            ],
        ),
        migrations.CreateModel(
            name='Geschaeftssummen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umfang', models.PositiveIntegerField()),
                ('jahr', models.PositiveIntegerField()),
                ('gueterArt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.GueterArten')),
            ],
        ),
    ]
