# Generated by Django 2.1.7 on 2019-04-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0010_geschaeftsjahressummen_geschaeftssummen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Geschaeftsjahressummen',
            new_name='Geschaeftslaendersummen',
        ),
    ]
