# Generated by Django 2.1.7 on 2019-04-24 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0011_auto_20190413_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='geschaeftslaendersummen',
            name='umfangJahr',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
