# Generated by Django 2.2 on 2019-04-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0012_geschaeftslaendersummen_umfangjahr'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaenderGruppen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Uebersetzungen')),
            ],
        ),
    ]
