# Generated by Django 2.2 on 2019-04-28 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0013_laendergruppen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laendergruppen',
            options={'verbose_name': 'Ländergruppe', 'verbose_name_plural': 'Ländergruppen'},
        ),
    ]
