# Generated by Django 2.2 on 2019-04-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0014_auto_20190428_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='laender',
            name='gruppen',
            field=models.ManyToManyField(to='exportkontrollstatistiken.Laendergruppen'),
        ),
    ]
