# Generated by Django 2.2 on 2019-04-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0015_laender_gruppen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportkontrollnummern',
            name='nummer',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='laender',
            name='gruppen',
            field=models.ManyToManyField(to='exportkontrollstatistiken.Laendergruppen'),
        ),
    ]
