# Generated by Django 2.2 on 2019-06-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0016_auto_20190430_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeschaefteCSVImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=20)),
                ('endempfaengerstaat', models.CharField(max_length=100)),
                ('gueterArt', models.CharField(max_length=100)),
                ('bewilligungstyp', models.CharField(max_length=100)),
                ('richtung', models.CharField(max_length=100)),
                ('ekn', models.CharField(max_length=100)),
                ('umfang', models.CharField(max_length=100)),
                ('importiert', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='laender',
            name='gruppen',
            field=models.ManyToManyField(to='exportkontrollstatistiken.Laendergruppen'),
        ),
    ]
