# Generated by Django 2.2 on 2019-06-22 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0017_auto_20190618_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='geschaeftecsvimport',
            name='beginn',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='geschaeftecsvimport',
            name='ende',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laender',
            name='gruppen',
            field=models.ManyToManyField(to='exportkontrollstatistiken.Laendergruppen'),
        ),
    ]
