# Generated by Django 2.2 on 2019-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0018_auto_20190622_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geschaefte',
            name='umfang',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='laender',
            name='gruppen',
            field=models.ManyToManyField(to='exportkontrollstatistiken.Laendergruppen'),
        ),
    ]
