# Generated by Django 3.0.3 on 2020-02-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0022_auto_20200214_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Manual check of entered data',
                'verbose_name_plural': 'Manual checks of entered data',
            },
        ),
        migrations.AlterField(
            model_name='geschaeftekriegsmaterialnachkategorieendempfaengerstaat',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exportkontrollstatistiken.Laendergruppen'),
        ),
        migrations.AlterField(
            model_name='laender',
            name='gruppen',
            field=models.ManyToManyField(to='exportkontrollstatistiken.Laendergruppen'),
        ),
        migrations.AddField(
            model_name='geschaeftekriegsmaterialnachkategorieendempfaengerstaat',
            name='checked',
            field=models.ManyToManyField(to='exportkontrollstatistiken.ManualCheck'),
        ),
    ]
