# Generated by Django 4.0.2 on 2022-03-10 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0024_auto_20200219_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bewilligungstypen',
            name='name',
        ),
        migrations.DeleteModel(
            name='GeschaefteCSVImport',
        ),
        migrations.DeleteModel(
            name='GeschaefteImport',
        ),
        migrations.RemoveField(
            model_name='geschaeftekriegsmaterialnachkategorieendempfaengerstaat',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='geschaeftekriegsmaterialnachkategorieendempfaengerstaat',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='geschaeftekriegsmaterialnachkategorieendempfaengerstaat',
            name='country',
        ),
        migrations.RemoveField(
            model_name='geschaeftekriegsmaterialnachkategorieendempfaengerstaat',
            name='sources',
        ),
        migrations.RemoveField(
            model_name='geschaeftsrichtungen',
            name='name',
        ),
        migrations.RemoveField(
            model_name='quellengeschaefte',
            name='name',
        ),
        migrations.RemoveField(
            model_name='geschaefte',
            name='bewilligungstyp',
        ),
        migrations.RemoveField(
            model_name='geschaefte',
            name='richtung',
        ),
        migrations.RemoveField(
            model_name='geschaefte',
            name='sources',
        ),
        migrations.DeleteModel(
            name='Bewilligungstypen',
        ),
        migrations.DeleteModel(
            name='GeschaefteKriegsmaterialNachKategorieEndempfaengerstaat',
        ),
        migrations.DeleteModel(
            name='Geschaeftsrichtungen',
        ),
        migrations.DeleteModel(
            name='QuellenGeschaefte',
        ),
    ]
