# Generated by Django 4.0.2 on 2022-03-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0025_remove_bewilligungstypen_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportkontrollnummern',
            name='nummer',
            field=models.CharField(max_length=30),
        ),
    ]
