# Generated by Django 4.0.2 on 2022-03-22 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0027_rename_laengengrad_laender_latitude_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManualCheck',
        ),
    ]
