# Generated by Django 4.0.3 on 2022-03-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exportkontrollstatistiken', '0028_delete_manualcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportkontrollnummern',
            name='nummer',
            field=models.CharField(max_length=50),
        ),
    ]
